bb_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from boulders.views import BoulderDetailApi, BoulderCreateApi
from rest_framework.authtoken import views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title = 'BB Clone API',
        default_version='v1'
    )
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gyms.urls')),
    path('boulder/', include('boulders.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/user', user_views.UserList.as_view(), name='user-list'),
    path('api/user/<int:pk>', user_views.UserDetail.as_view(), name='user-detail'),
    path('api/group', user_views.GroupList.as_view(), name='group-list' ),
    path('api/group/<int:pk>', user_views.GroupDetail.as_view(), name='group-detail'),
    path('api/boulder/<int:pk>', BoulderDetailApi.as_view(), name='boulder-detail'),
    path('api/boulder', BoulderCreateApi.as_view(), name='boulder-create'),
    path('api/auth', views.obtain_auth_token, name='auth-token'),
    path('api', schema_view.with_ui('swagger'), name='api-doc')
]

gyms/urls.py
from django.urls import path
from . import views
from .views import GymListView, GymCreateView, GymUpdateView, GymDeleteView, BoulderListView, GymListApi, GymDetailApi
from boulders.views import BoulderCreateView
from walls.views import WallListView, WallCreateView, WallUpdateView, WallDeleteView, WallCreateApi, WallDetailApi

urlpatterns = [
    path('', GymListView.as_view(), name='home'),
    path('gym/<int:pk>', BoulderListView.as_view(), name='gym_detail'),
    path('gym/<int:gym_pk>/create', BoulderCreateView.as_view(), name='boulder_create'),
    path('gym/<int:gym_pk>/walls', WallListView.as_view(), name='wall_list'),
    path('gym/<int:gym_pk>/walls/create', WallCreateView.as_view(), name='wall_create'),
    path('walls/<int:pk>/delete', WallDeleteView.as_view(), name='wall_delete'),
    path('walls/<int:pk>/update', WallUpdateView.as_view(), name='wall_update'),
    path('api/wall', WallCreateApi.as_view(), name='wall-create'),
    path('api/wall/<int:pk>', WallDetailApi.as_view(), name='wall-detail'),
    path('gym/create', GymCreateView.as_view(), name='gym_create'),
    path('gym/<int:pk>/update', GymUpdateView.as_view(), name='gym_update'),
    path('gym/<int:pk>/delete', GymDeleteView.as_view(), name='gym_delete'),
    path('api/gym', GymListApi.as_view(), name='gym-list'), 
    path('api/gym/<int:pk>', GymDetailApi.as_view(), name='gym-detail'),
]

boulders/models.py
from django.db import models
from walls.models import Wall
from django.contrib.auth.models  import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.urls import reverse
from datetime import date

# Create your models here.
class Boulder(models.Model):
    '''
    A Django model for the Boulder object.

    Attributes
    ----
    boulder_name: string
        Name of the boulder problem.
    wall: Wall
        The Wall on which the boulder is set.
    setter: User
        The User who created the boulder problem.
    '''
    wall = models.ForeignKey(Wall, on_delete=models.CASCADE)
    boulder_name = models.CharField(max_length=100)
    setter = models.ForeignKey(User, on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(17)])

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['boulder_name', 'wall'], name='unique_boulder_name_per_wall'
            )
        ]

    def __str__(self):
        return self.boulder_name
    
    def get_absolute_url(self):
        return reverse('boulder_detail', kwargs={'pk': self.pk})


class Annotation(models.Model):
    boulder = models.ForeignKey(Boulder, on_delete=models.CASCADE)
    coord_x = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    coord_y = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    radius = models.FloatField(validators=[MinValueValidator(0.0)])

    def __str__(self):
        return f"[({self.coord_x}, {self.coord_y}),{self.radius}]"

class Sender(models.Model):
    boulder = models.ForeignKey(Boulder, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    flash = models.BooleanField()
    date = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.boulder.boulder_name} was sent by {self.sender.username}"

gyms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Gym(models.Model):
    '''
    A Django model to represent the Gym object.

    Attributes
    ----
    name: string
        Name of the Gym
    address: string
        Address of the Gym
    staff: User
        User associated with the Gym. Only this User can edit gym details and images.
    '''
    name = models.CharField(max_length=100)
    addr = models.CharField(max_length=255)
    staff = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['name'], name='unique_gym_name'
            )
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('gym_detail', kwargs={'pk': self.pk})

gyms/views.py
from collections.abc import Sequence
from django.shortcuts import render
from .models import Gym
from boulders.models import Boulder
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from itertools import islice
from rest_framework import generics
from rest_framework.permissions import IsAuthenticatedOrReadOnly, BasePermission, SAFE_METHODS
from .serializers import GymSerializer

# Create your views here.

class GymListView(ListView):
    model = Gym
    context_object_name = 'gyms'
    paginate_by = 4

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'name')
        return ordering
    
    def get_queryset(self):
        ordering = self.get_ordering()
        gyms = Gym.objects.all().order_by(ordering)
        query = self.request.GET.get('query', '')
        if query:
            gyms = gyms.filter(name__icontains=query).order_by(ordering)
        return gyms
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ordering'] = self.get_ordering()
        query  = self.request.GET.get('query', '')
        if query:
            context['query'] = query
        return context

class GymDetailView(DetailView):
    model = Gym
    context_object_name = 'gym'

    def boulder_search_generator(self, query, gym):
        for boulder in Boulder.objects.filter(wall__gym = gym, boulder_name__icontains=query).order_by('boulder_name').iterator():
            yield boulder

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('query', '')
        pagination = self.request.GET.get('page', '0')
        if query:
            if int(pagination) == 0:
                boulders = self.boulder_search_generator(query, context['gym'])
            else:
                boulders = islice(self.boulder_search_generator(query, context['gym']), (5 * int(pagination)), None)
            
            context['boulders'] = []
            try:
                for _ in range(5):
                    context['boulders'].append(next(boulders))
                context['next_button'] = True
            except StopIteration:
                pass
        else:
            context["boulders"] = Boulder.objects.all().filter(wall__gym = context['gym'])
        return context

class BoulderListView(ListView):
    model = Boulder
    # template_name = 'gyms/boulder_list.html'
    context_object_name = 'boulders'
    paginate_by = 5

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'boulder_name')
        return ordering

    def get_queryset(self):
        ordering = self.get_ordering()
        boulders = Boulder.objects.all().filter(wall__gym__pk = self.kwargs['pk']).order_by(ordering)
        query = self.request.GET.get('query', '')
        if query != '':
            boulders = boulders.filter(boulder_name__icontains = query).order_by(ordering)
        return boulders
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['gym'] = Gym.objects.get(pk = self.kwargs['pk'])
        context['ordering'] = self.get_ordering()
        query = self.request.GET.get('query', '')
        if query:
            context['query'] = query
        return context

class GymCreateView(LoginRequiredMixin, CreateView):
    model = Gym
    fields = ['name', 'addr']

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)

class GymUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Gym
    fields = ['name', 'addr']
    template_name = 'gyms/gym_update_form.html'

    def form_valid(self, form):
        form.instance.staff = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        gym = self.get_object()
        if self.request.user == gym.staff:
            return True
        return False

class GymDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Gym
    success_url = '/'

    def test_func(self):
        gym = self.get_object()
        if self.request.user == gym.staff:
            return True
        return False

class GymStaffOrReadOnly(BasePermission): 
    def has_object_permission(self, request, view, obj):
        if request.method in SAFE_METHODS:
            return True
        return obj.staff == request.user

class IsStaffUserOrReadOnly(BasePermission):
    def has_permission(self, request, view):
        if request.method in SAFE_METHODS:
            return True
        return request.user.groups.filter(name='StaffUser').exists()

class GymListApi(generics.ListCreateAPIView):
    permission_classes = [IsStaffUserOrReadOnly]
    queryset = Gym.objects.all()
    serializer_class = GymSerializer

class GymDetailApi(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [GymStaffOrReadOnly]
    queryset = Gym.objects.all()
    serializer_class = GymSerializer

gyms/templates/gyms/gym.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1 class="text-center">{{ gym.name }}</h1>
        <h3 class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
            </svg>
            {{ gym.addr }}
        </h3>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-8">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row justify-content-center">
                        <i class="text-center col-sm-1">Ascents</i><strong class="col-sm-3 text-center"><i>Boulders</i></strong> <i class="col-sm-1">Grade</i><span class="col-sm-2">Wall</span>
    
                    </div>
                </li>
                {% for boulder in boulders %}
                    <li class="list-group-item">
                        <div class="row justify-content-center">
                            <i class="text-center col-sm-1">{{ boulder.sender_set.count }}</i> <strong class="col-sm-3 text-center"><a href="../boulder/{{ boulder.pk }}">{{ boulder.boulder_name }}</a></strong> <i class="col-sm-1">V{{ boulder.grade }}</i><span class="col-sm-2">{{ boulder.wall.wall_name}}</span></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    

{% endblock %}

gyms/templates/gyms/gym_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group my-3">
                    <legend class="border-bottom mb-3">Delete Gym</legend>
                    <h2>Are you sure you want to delete the gym "{{ object.name }}"</h2>
                </fieldset>
                <div class="form-group my-2">
                    <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                    <a class="btn btn-outline-dark" href="{% url 'gym_detail' object.id %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

gyms/templates/gyms/gym_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group my-3">
                    <legend class="border-bottom mb-3">Create a new gym</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group my-2">
                    <button class="btn btn-dark" type="submit">Create</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

gyms/templates/gyms/gym_list.html
{% extends "base.html" %}
{% load auth_extras %}
{% load range_tag %}

{% block content %}
    <h1 class="text-center">All Gyms</h1> 
    <div class="row ordering my-2">
        <div class="col-md-4 col-6">
            Sort By:
            <div class="btn-group-sm btn-group" role="group">
                <a href="?ordering=name{% if query %}&query={{ query }}{% endif %}" class="btn btn-outline-dark {% if ordering == 'name' %} active {% endif %}">Name</a>
                <a href="?ordering=addr{% if query %}&query={{ query }}{% endif %}" class="btn btn-outline-dark {% if ordering == 'addr' %} active {% endif %}">Location</a>
            </div>
        </div>
        {% if user.is_authenticated %}
            {% if user|has_group:"StaffUser" %}
                <div class="col-2 offset-4 col-md-1 offset-md-7">
                    <a href="{% url 'gym_create' %}" type="button" class="btn btn-sm btn-dark">
                        Create
                    </a>
                </div>
            {% endif %}
        {% endif %}
    </div> 
    <div class="row">
        {% for gym in gyms %}
            <div class="col-12 col-sm-6 col-lg-3 px-3 px-sm-2 py-1">
                <div class="card text-center" >
                    <div class="card-body">
                        <h5 class="card-title">{{ gym.name }}</h5>
                        <p class="card-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                                <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                            </svg>
                            {{ gym.addr }}
                        </p>
                        <a href="gym/{{ gym.pk }}" class="btn btn-dark">View Boulders</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination row my-2">
        <div class="btn-toolbar col-12 justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group">
                {% for page_num in page_obj.paginator.num_pages|times %}
                    <a href="?page={{page_num}}{% if query %}&query={{ query }}{% endif %}" class="btn btn-sm btn-outline-dark {% if page_num == page_obj.number %}active{% endif %}">{{ page_num }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

gyms/templates/gyms/gym_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group my-3">
                    <legend class="border-bottom mb-3">Update Gym</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group my-2">
                    <button class="btn btn-dark" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

gyms/templates/gyms/home.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center">View all gyms</h1> 
    <div class="row">
        {% for gym in gyms %}
            <div class="col-sm-3" style="padding: 1%;">
                <div class="card text-center" >
                    <div class="card-body">
                        <h5 class="card-title">{{ gym.name }}</h5>
                        <p class="card-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                                <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                            </svg>
                            {{ gym.addr }}
                        </p>
                        <a href="gym/{{ gym.pk }}" class="btn btn-primary">View Boulders</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}