bb_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from boulders.views import BoulderDetailApi, BoulderCreateApi
from rest_framework.authtoken import views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title = 'BB Clone API',
        default_version='v1'
    )
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gyms.urls')),
    path('boulder/', include('boulders.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/user', user_views.UserList.as_view(), name='user-list'),
    path('api/user/<int:pk>', user_views.UserDetail.as_view(), name='user-detail'),
    path('api/group', user_views.GroupList.as_view(), name='group-list' ),
    path('api/group/<int:pk>', user_views.GroupDetail.as_view(), name='group-detail'),
    path('api/boulder/<int:pk>', BoulderDetailApi.as_view(), name='boulder-detail'),
    path('api/boulder', BoulderCreateApi.as_view(), name='boulder-create'),
    path('api/auth', views.obtain_auth_token, name='auth-token'),
    path('api', schema_view.with_ui('swagger'), name='api-doc')
]

boulders/urls.py
from django.urls import path
from .views import BoulderDetailView, BoulderUpdateView, BoulderDeleteView, BoulderDetailApi, SenderDeleteView, SenderCreateView

urlpatterns = [
    path('<int:pk>/', BoulderDetailView.as_view(), name='boulder_detail'),
    path('<int:pk>/update', BoulderUpdateView.as_view(), name='boulder_update'),
    path('<int:pk>/delete', BoulderDeleteView.as_view(), name='boulder_delete'),
    path('<int:gym_pk>/deletesend/<int:pk>', SenderDeleteView.as_view(), name='sender_delete'),
    path('<int:pk>/createsend', SenderCreateView.as_view(), name='sender_create'),
    # path('api/boulder/<int:pk>', BoulderDetailApi.as_view(), name='boulder-detail')

]

gyms/urls.py
from django.urls import path
from . import views
from .views import GymListView, GymCreateView, GymUpdateView, GymDeleteView, BoulderListView, GymListApi, GymDetailApi
from boulders.views import BoulderCreateView
from walls.views import WallListView, WallCreateView, WallUpdateView, WallDeleteView, WallCreateApi, WallDetailApi

urlpatterns = [
    path('', GymListView.as_view(), name='home'),
    path('gym/<int:pk>', BoulderListView.as_view(), name='gym_detail'),
    path('gym/<int:gym_pk>/create', BoulderCreateView.as_view(), name='boulder_create'),
    path('gym/<int:gym_pk>/walls', WallListView.as_view(), name='wall_list'),
    path('gym/<int:gym_pk>/walls/create', WallCreateView.as_view(), name='wall_create'),
    path('walls/<int:pk>/delete', WallDeleteView.as_view(), name='wall_delete'),
    path('walls/<int:pk>/update', WallUpdateView.as_view(), name='wall_update'),
    path('api/wall', WallCreateApi.as_view(), name='wall-create'),
    path('api/wall/<int:pk>', WallDetailApi.as_view(), name='wall-detail'),
    path('gym/create', GymCreateView.as_view(), name='gym_create'),
    path('gym/<int:pk>/update', GymUpdateView.as_view(), name='gym_update'),
    path('gym/<int:pk>/delete', GymDeleteView.as_view(), name='gym_delete'),
    path('api/gym', GymListApi.as_view(), name='gym-list'), 
    path('api/gym/<int:pk>', GymDetailApi.as_view(), name='gym-detail'),
]

boulders/models.py
from django.db import models
from walls.models import Wall
from django.contrib.auth.models  import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.urls import reverse
from datetime import date

# Create your models here.
class Boulder(models.Model):
    '''
    A Django model for the Boulder object.

    Attributes
    ----
    boulder_name: string
        Name of the boulder problem.
    wall: Wall
        The Wall on which the boulder is set.
    setter: User
        The User who created the boulder problem.
    '''
    wall = models.ForeignKey(Wall, on_delete=models.CASCADE)
    boulder_name = models.CharField(max_length=100)
    setter = models.ForeignKey(User, on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(17)])

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['boulder_name', 'wall'], name='unique_boulder_name_per_wall'
            )
        ]

    def __str__(self):
        return self.boulder_name
    
    def get_absolute_url(self):
        return reverse('boulder_detail', kwargs={'pk': self.pk})


class Annotation(models.Model):
    boulder = models.ForeignKey(Boulder, on_delete=models.CASCADE)
    coord_x = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    coord_y = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    radius = models.FloatField(validators=[MinValueValidator(0.0)])

    def __str__(self):
        return f"[({self.coord_x}, {self.coord_y}),{self.radius}]"

class Sender(models.Model):
    boulder = models.ForeignKey(Boulder, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    flash = models.BooleanField()
    date = models.DateField(default=date.today)

    def __str__(self):
        return f"{self.boulder.boulder_name} was sent by {self.sender.username}"

boulders/forms.py
from django import forms
from gyms.models import Gym
from walls.models import Wall
from boulders.models import Boulder
from django.shortcuts import get_object_or_404

class BoulderCreateForm(forms.ModelForm):
   
    def __init__(self, *args, gym_pk=None, **kwargs):
        self.gym_pk = gym_pk
        super(BoulderCreateForm, self).__init__(*args, **kwargs)

        # gym = Gym.objects.get(pk = self.gym_pk)
        gym = get_object_or_404(Gym, pk=self.gym_pk)
        self.fields['wall'].queryset = Wall.objects.filter(gym = gym )
    
    class Meta:
        model = Boulder
        fields = ['boulder_name', 'grade' , 'wall']

    boulder_name = forms.CharField()
    grade = forms.IntegerField()
    wall = forms.ModelChoiceField(queryset=None)

class BoulderUpdateForm(forms.ModelForm):

    def __init__(self, *args,gym=None, **kwargs):
        self.gym = gym
        super(BoulderUpdateForm, self).__init__(*args, **kwargs)
        self.fields['wall'].queryset = gym.wall_set.all()
    
    class Meta:
        model = Boulder
        fields = ['boulder_name', 'grade', 'wall']
    
    boulder_name = forms.CharField()
    grade = forms.IntegerField()
    wall = forms.ModelChoiceField(queryset=None)

boulders/views.py
from .models import Boulder, Sender
from gyms.models import Gym
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .forms import BoulderCreateForm, BoulderUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework.permissions import BasePermission, IsAuthenticated, SAFE_METHODS
from .serializers import BoulderSerializer

# Create your views here.

class BoulderDetailView(DetailView):
    model = Boulder
    context_object_name = 'boulder'

    def get_context_data(self, **kwargs):
        context = super(BoulderDetailView, self).get_context_data(**kwargs)
        context['user_has_sent'] = False
        for sender in context['boulder'].sender_set.all():
            if sender.sender == self.request.user:
                context['user_has_sent'] = True
                context['sender_pk'] = sender.pk
        return context


class BoulderCreateView(LoginRequiredMixin, CreateView):

    model = Boulder
    # fields = ['boulder_name', 'wall', 'grade']
    form_class = BoulderCreateForm 

    def get_form_kwargs(self):
        kwargs = super(BoulderCreateView, self).get_form_kwargs()
        kwargs['gym_pk'] = self.kwargs['gym_pk']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(BoulderCreateView, self).get_context_data(**kwargs)
        # context['gym_name'] = Gym.objects.get(pk=self.kwargs["gym_pk"]).name
        gym = get_object_or_404(Gym, pk=self.kwargs["gym_pk"])
        context["gym_name"] = gym.name
        if len(gym.wall_set.all()) == 0:
            context['has_walls'] = False
        else:
            context['has_walls'] = True
        return context
    
    def form_valid(self, form):
        form.instance.setter = self.request.user
        return super().form_valid(form)

class BoulderUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Boulder
    form_class = BoulderUpdateForm
    template_name = 'boulders/boulder_update_form.html'

    def get_form_kwargs(self):
        kwargs = super(BoulderUpdateView,self).get_form_kwargs()
        kwargs['gym'] = self.get_object().wall.gym
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super(BoulderUpdateView, self).get_context_data(**kwargs)
        context['gym_name'] = self.get_object().wall.gym.name
        return context

    def form_valid(self, form):
        form.instance.setter = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        boulder = self.get_object()
        if self.request.user == boulder.setter:
            return True
        return False
    
class BoulderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Boulder
    
    def get_success_url(self):
        gym_pk = self.get_object().wall.gym.pk
        return reverse('gym_detail', kwargs={'pk': gym_pk})

    def test_func(self):
        boulder = self.get_object()
        if self.request.user == boulder.setter:
            return True
        return False

class SenderCreateView(LoginRequiredMixin, CreateView):
    model = Sender
    fields = ['flash']
    template_name = 'base.html'

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.boulder = Boulder.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('boulder_detail', kwargs={'pk': self.kwargs['pk']})

class SenderDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Sender

    def get_success_url(self):
        pk = self.get_object().boulder.pk
        return reverse('boulder_detail', kwargs={'pk': pk})

    def test_func(self):
        sender = self.get_object().sender
        if self.request.user == sender:
            return True
        return False

class BoulderSetterOrReadOnly(BasePermission):
    def has_object_permission(self, request, view, obj):
        if request.method in SAFE_METHODS:
            return True
        return obj.setter == request.user

class BoulderDetailApi(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [BoulderSetterOrReadOnly]
    queryset = Boulder.objects.all()
    serializer_class = BoulderSerializer

class BoulderCreateApi(generics.CreateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = Boulder.objects.all()
    serializer_class = BoulderSerializer

boulders/templates/boulders/boulder.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1 class="text-center">{{ boulder.boulder_name }} <i>(V{{ boulder.grade }})</i></h1>
        <h5 class="text-center">{{ boulder.wall.wall_name }} at  {{ boulder.wall.gym.name }}</h5>
    </div>
    <div class="row justify-content-center">
        <canvas id="ctx" width="{{ boulder.wall.img_height }}" height="{{ boulder.wall.img_width }}" style='width:{{ boulder.wall.img_width }}px; height:{{ boulder.wall.img_height }}px;'></canvas>
    </div>

    <script>
        var myCanvas = document.getElementById('ctx');
        var ctx = myCanvas.getContext('2d');
        var img = new Image;
        img.onload = function(){
            ctx.drawImage(img,0,0); // Or at whatever offset you like
            
            {% for annotation in annotations %}
                ctx.beginPath();
                ctx.arc({{ annotation.coord_x }}, {{ annotation.coord_y }}, {{ annotation.radius }}, 0, 2 * Math.PI, true);
                ctx.lineWidth = 5;
                ctx.strokeStyle = '#FDDA0D';
                ctx.stroke();
                ctx.closePath();
            {% endfor %}
        };
        img.src = "{{ boulder.wall.img_url }}";

        
    </script>

    
{% endblock %}

boulders/templates/boulders/boulder_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group my-3">
                    <legend class="border-bottom mb-3">Delete Boulder</legend>
                    <h2>Are you sure you want to delete the boulder "{{ object.boulder_name }}"</h2>
                </fieldset>
                <div class="form-group my-3">
                    <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                    <a class="btn btn-outline-dark" href="{% url 'boulder_detail' object.id %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

boulders/templates/boulders/boulder_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row mb-3">
        <h1 class="text-center">{{ boulder.boulder_name }} <i>({{ boulder.grade }})</i></h1>
        <h5 class="text-center">{{ boulder.wall.wall_name }} at  {{ boulder.wall.gym.name }}</h5>
    </div>
    {% if user.is_authenticated %}
        {% if boulder.setter == user %}
            <div class="row mb-3 justify-content-center">
                <div class="col-2">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Manage Boulder
                        </button>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'boulder_update' pk=boulder.pk %}">Update Boulder</a></li>
                        <li><a class="dropdown-item" href="{% url 'boulder_delete' pk=boulder.pk %}">Delete Boulder</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endif %}
    <div class="row justify-content-center mb-3">
        <div class="col-12 col-md-7">
            <canvas id="ctx" width="{{ boulder.wall.img_height }}" height="{{ boulder.wall.img_width }}" style='width:{{ boulder.wall.img_width }}px; height:{{ boulder.wall.img_height }}px;'></canvas>
        </div>
        <div class="col-12 col-md-3">
            <h4>Ascents</h4>
            <ul class="list-group">
                {% for sender in boulder.sender_set.all %}
                    <li class="list-group-item">
                        <span class="badge text-bg-dark rounded-pill col-2">
                            {% if sender.flash %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge" viewBox="0 0 16 16"><path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09zM4.157 8.5H7a.5.5 0 0 1 .478.647L6.11 13.59l5.732-6.09H9a.5.5 0 0 1-.478-.647L9.89 2.41z"/></svg>
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/><path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/></svg>
                            {% endif %}
                        </span>
                        <span class="col-4 text-center">
                            <strong>
                                {{sender.sender.username}}
                            </strong>
                        </span>
                        <span class="col-1">
                            <small>
                                {{sender.date}}
                            </small>
                        </span>
                    </li>
                {% endfor %}
            </ul>
            {% if user.is_authenticated %}
                {% if user_has_sent %}
                    <form method="POST" action={% url "sender_delete" pk=sender_pk gym_pk=boulder.pk %} class="mt-3">
                        {% csrf_token %}
                        <input class='btn btn-dark' type="submit" value="Remove Ascent">
                    </form>

                {% else %}
                    <form method="POST" action={% url "sender_create" pk=boulder.pk %} class="mt-3">
                        {% csrf_token %}
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" name="flash"><label class="form-check-label">Flash?</label>
                        </div>
                        <input class="btn btn-dark" type="submit" value="Log Ascent">
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <script>
        var myCanvas = document.getElementById('ctx');
        var ctx = myCanvas.getContext('2d');
        var img = new Image;
        img.onload = function(){
            ctx.drawImage(img,0,0); // Or at whatever offset you like
            
            {% for annotation in boulder.annotation_set.all %}
                ctx.beginPath();
                ctx.arc({{ annotation.coord_x }}, {{ annotation.coord_y }}, {{ annotation.radius }}, 0, 2 * Math.PI, true);
                ctx.lineWidth = 5;
                ctx.strokeStyle = '#FDDA0D';
                ctx.stroke();
                ctx.closePath();
            {% endfor %}
        };
        img.src = "{{ boulder.wall.img_url }}";

        
    </script>

    
{% endblock %}

boulders/templates/boulders/boulder_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            {% if has_walls %}
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group my-3">
                        <legend class="border-bottom mb-3">Create a new boulder at {{ gym_name }}</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group my-2">
                        <button class="btn btn-dark" type="submit">Create</button>
                    </div>
                </form>
            {% else %}
                <h1>The Gym Staff needs to add a wall before you can create boulders.</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

boulders/templates/boulders/boulder_list.html
{% extends "base.html" %}
{% block content %}
{% load range_tag %}
    <div>
        <h1 class="text-center">{{ gym.name }}</h1>
        <h3 class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
                <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A32 32 0 0 1 8 14.58a32 32 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10"/>
                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4m0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
            </svg>
            {{ gym.addr }}
        </h3>
    </div>
    <div class="row justify-content-center">
        <div class="row ordering my-2">
            <div class="col-md-4 col-5 offset-1">
                Sort By:
                <div class="btn-group-sm btn-group" role="group">
                    <a href="?ordering=boulder_name{% if query %}&query={{ query }}{% endif %}" class="btn btn-outline-dark {% if ordering == 'boulder_name' %} active {% endif %}">Name</a>
                    <a href="?ordering=grade{% if query %}&query={{ query }}{% endif %}" class="btn btn-outline-dark {% if ordering == 'grade' %} active {% endif %}">Grade</a>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div class="btn-group btn-group-sm col-3 offset-1 col-md-2 offset-md-3 offser-lg-5" role="group">
                    <a class="btn btn-outline-dark" href="{% url 'boulder_create' gym_pk=gym.pk%}">Create</a>
                    {% if gym.staff == user %}
                        <div class="btn-group btn-group-sm " role="group">
                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Staff Controls
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'wall_list' gym_pk=gym.pk %}">Manage Walls</a></li>
                                <li><a class="dropdown-item" href="{% url 'gym_update' pk=gym.pk %}">Update Gym</a></li>
                                <li><a class="dropdown-item" href="{% url 'gym_delete' pk=gym.pk %}">Delete Gym</a></li>
                            </ul>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>

        <div class="row justify-content-center">
            <div class="col-md-9 col-12">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row justify-content-center">
                            <i class="text-center d-none d-lg-block col-sm-1">Ascents</i><strong class="col-9 col-md-3 text-center"><i>Boulders</i></strong> <i class="col-3 col-md-2">Grade</i><span class="col-sm-2 col-md-3 d-none d-md-block">Wall</span>
                        </div>
                    </li>
                    {% for boulder in boulders %}
                        <li class="list-group-item">
                            <div class="row justify-content-center">
                                <i class="text-center d-none d-lg-block col-sm-1">{{ boulder.sender_set.count }}</i> <strong class="col-9 col-md-3 text-center"><a style="color: black;" href="../boulder/{{ boulder.pk }}">{{ boulder.boulder_name }}</a></strong> <i class="col-3 col-md-2">{{ boulder.grade }}</i><span class="col-sm-2 col-md-3 d-none d-md-block">{{ boulder.wall.wall_name}}</span></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="pagination row my-2">
            <div class="btn-toolbar col-12 justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group me-2" role="group">
                    {% for page_num in page_obj.paginator.num_pages|times %}
                        <a href="?page={{page_num}}{% if query %}&query={{ query }}{% endif %}" class="btn btn-sm btn-outline-dark {% if page_num == page_obj.number %}active{% endif %}">{{ page_num }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


    <!-- {% if user.is_authenticated %}
        <div>
            <a href="{% url 'boulder_create' gym_pk=gym.pk%}">Create Boulder</a>
        </div>
        {% if gym.staff == user %}
            <div>
                <a href="{% url 'wall_list' gym_pk=gym.pk %}">Manage Walls</a>
            </div>
            <div>
                <a href="{% url 'gym_delete' pk=gym.pk %}">Delete Gym</a>
            </div>
            <div>
                <a href="{% url 'gym_update' pk=gym.pk %}">Update Gym</a>
            </div>
        {% endif %}
    {% endif %}
     -->

{% endblock %}

boulders/templates/boulders/boulder_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section justify-content-center row">
        <div class="col-10 col-md-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group my-3">
                    <legend class="border-bottom mb-3">Update boulder at {{ gym_name }}</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group my-2">
                    <button class="btn btn-dark" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}